# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_time', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('department', models.CharField(max_length=250)),
                ('summary', models.TextField()),
                ('background', models.TextField()),
                ('supplemental', models.TextField()),
                ('sponsors', models.CharField(max_length=250)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.Agenda')),
            ],
        ),
        migrations.CreateModel(
            name='AgendaRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.TextField()),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.AgendaItem')),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.Committee'),
        ),
    ]
