# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-15 04:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendaitem',
            old_name='background',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='agendaitem',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='agendaitem',
            name='supplemental',
        ),
    ]
