# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_auto_20170918_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaitem',
            name='background',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='sponsors',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='supplemental',
            field=models.TextField(null=True),
        ),
    ]
