# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-21 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_change_sendmessage_first_last'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pro',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
