# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-03 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0003_agendaitem_new_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendaitem',
            name='body',
        ),
    ]
