# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-17 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0003_auto_20180214_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaitem',
            name='meeting_time',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
