# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-03 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0004_remove_agendaitem_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendaitem',
            old_name='new_body',
            new_name='body',
        ),
    ]
