# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-06 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0004_add_fileds_to_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageuserprofile',
            name='business_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engageuserprofile',
            name='child_school',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engageuserprofile',
            name='home_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engageuserprofile',
            name='resident',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engageuserprofile',
            name='school',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engageuserprofile',
            name='works',
            field=models.BooleanField(default=False),
        ),
    ]
