# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-03 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0005_auto_20180303_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaitem',
            name='meeting_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
