# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-08 05:46
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0005_add_fields_to_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendarecommendation',
            name='recommendation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[], size=None),
        ),
    ]
