# Generated by Django 2.0.7 on 2018-07-11 00:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0006_change_recommendations_to_array'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='committee',
            field=models.ForeignKey(on_delete='CASCADE', to='ingest.Committee'),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='agenda',
            field=models.ForeignKey(on_delete='CASCADE', related_name='items', to='ingest.Agenda'),
        ),
        migrations.AlterField(
            model_name='agendarecommendation',
            name='agenda_item',
            field=models.ForeignKey(on_delete='CASCADE', related_name='recommendations', to='ingest.AgendaItem'),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='committee',
            field=models.ForeignKey(on_delete='CASCADE', related_name='members', to='ingest.Committee'),
        ),
        migrations.AlterField(
            model_name='engageuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='message',
            name='agenda_item',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='ingest.AgendaItem'),
        ),
        migrations.AlterField(
            model_name='message',
            name='committee',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='ingest.Committee'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
