# Generated by Django 2.0.7 on 2018-07-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0007_update-django'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendaitem',
            name='meeting_id',
        ),
        migrations.AddField(
            model_name='agenda',
            name='meeting_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
