# Generated by Django 2.0.7 on 2018-08-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0009_update_authcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='cutoff_hour',
            field=models.PositiveIntegerField(default=11),
        ),
        migrations.AddField(
            model_name='committee',
            name='cutoff_minute',
            field=models.PositiveIntegerField(default=59),
        ),
        migrations.AddField(
            model_name='committee',
            name='cutoff_offset_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
