# Generated by Django 2.0.7 on 2018-07-31 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0009_update_authcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnicity', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='ethnicity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ingest.Ethnicity'),
        ),
    ]
