# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-28 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0010_add_items_to_messages2'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ethnicity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
