# Generated by Django 2.0.7 on 2018-08-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0010_add_cutoff_to_committee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='cutoff_offset_days',
            field=models.IntegerField(default=0),
        ),
    ]
