# Generated by Django 2.0.7 on 2018-07-31 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0010_auto_20180730_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ethnicity',
            old_name='ethnicity',
            new_name='name',
        ),
    ]
