# Generated by Django 2.0.7 on 2018-08-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0011_auto_20180730_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='ethnicity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Ethnicity',
        ),
    ]
