# Generated by Django 2.0.7 on 2018-08-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0012_remove_ethnicity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engageuserprofile',
            name='ethnicity',
        ),
        migrations.AlterField(
            model_name='engageuserprofile',
            name='authcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
