# Generated by Django 2.0.7 on 2018-08-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0013_remove_eth_add_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='location_lat',
            field=models.FloatField(default=34.024212),
        ),
        migrations.AddField(
            model_name='committee',
            name='location_lng',
            field=models.FloatField(default=-118.496475),
        ),
    ]
