# Generated by Django 2.0.7 on 2018-08-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0014_add_location_to_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
