# Generated by Django 2.0.7 on 2018-08-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0014_auto_20180811_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ethnicity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
