# Generated by Django 2.0.7 on 2018-08-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0015_message_ethnicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageuserprofile',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
