# Generated by Django 2.0.7 on 2018-09-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0016_add_tz_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
