"""
Django settings for CouncilTag project.

Generated by 'django-admin startproject' using Django 1.11.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import dj_database_url
import django_heroku

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
if os.environ.get("CouncilTag") == 'local':
    DEBUG = True
print(DEBUG)
ALLOWED_HOSTS = ['localhost', 'https://engage-santa-monica.herokuapp.com',
                 'engage.town', 'engage-backend.herokuapp.com', '127.0.0.1']
APPEND_SLASH=True
# Application definition
print("Opened settings")
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'CouncilTag.ingest',
    'rest_framework',
    'CouncilTag.api',
    'corsheaders',
    'drf_yasg',
    'drf_openapi'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning',
    'DEFAULT_AUTHENTICATION_CLASSES': ['rest_framework.authentication.SessionAuthentication'],
}
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'name': 'Authentication',
            'type': 'apiKey',
            'in': 'header',
        }
    },
    'USE_SESSION_AUTH': True,
    
}

ROOT_URLCONF = 'CouncilTag.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CouncilTag.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get("DB_NAME"),
            'USER': os.environ.get("DB_USER"),
            'PASSWORD': os.environ.get("DB_PASS"),
            'HOST': 'localhost',
            'TEST': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': os.environ.get("TEST_DB_NAME"),
                'USER': os.environ.get("TEST_DB_USER"),
                'PASSWORD': os.environ.get("TEST_DB_PASS"),
                'HOST': 'localhost',
            },
        },
    }
else:
    DATABASES = {}
    DATABASES['default'] = dj_database_url.config(
        conn_max_age=600, ssl_require=True)
    DATABASES['default']['TEST'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get("TEST_DB_NAME"),
        'USER': os.environ.get("TEST_DB_USER"),
        'PASSWORD': os.environ.get("TEST_DB_PASS"),
        'HOST': 'localhost',
    }
print(os.environ.get('DATABASE_URL'))
# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))

STATIC_ROOT = os.path.join(PROJECT_ROOT, 'staticfiles')
STATIC_URL = '/static/'

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = (
    os.path.join(PROJECT_ROOT, 'static'),
)
STATICFILES_STORAGE = 'whitenoise.django.GzipManifestStaticFilesStorage'

CORS_ORIGIN_ALLOW_ALL = True
AUTHENTICATION_BACKENDS = ['CouncilTag.api.backends.EmailPasswordBackend']
AUTH_USER_MODEL = 'ingest.EngageUser'

CORS_URLS_REGEX = r'^/api/.*$'

if DEBUG:
    COUNCIL_CLERK_EMAIL = 'shariq.torres@gmail.com'
else:
    COUNCIL_CLERK_EMAIL = 'counciltag@gmail.com'

# According to Heroku, this should be at the end of settings.py
django_heroku.settings(locals())

if os.environ.get("CouncilTag") == 'local':
    # Display output of the email in the console
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.sendgrid.net'
    EMAIL_HOST_USER = os.environ.get('USERNAME')
    EMAIL_HOST_PASSWORD = os.environ.get('PASSWORD')
    EMAIL_PORT = 587
    EMAIL_USE_TLS = False
    EMAIL_USE_TLS = False
    EMAIL_USE_SSL = False
    EMAIL_TIMEOUT = False
    EMAIL_SSL_KEYFILE = False
    EMAIL_SSL_CERTFILE = False