# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 04:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('injest', '0005_engageuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
