# Generated by Django 2.0.12 on 2019-06-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0005_auto_20190626_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='cutoff_time',
            field=models.PositiveIntegerField(default=1561534147.077827),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='pdf_time',
            field=models.PositiveIntegerField(default=1561534147.077881),
        ),
    ]
