# Generated by Django 2.0.12 on 2019-06-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0006_auto_20190626_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='cutoff_time',
            field=models.PositiveIntegerField(default=1561535667.543189),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='pdf_time',
            field=models.PositiveIntegerField(default=1561535667.543237),
        ),
    ]
