# Generated by Django 2.0.12 on 2019-06-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0013_auto_20190626_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='cutoff_time',
            field=models.PositiveIntegerField(default=1561573277.069483),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='pdf_time',
            field=models.PositiveIntegerField(default=1561573277.069531),
        ),
    ]
