# Generated by Django 2.0.12 on 2019-06-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0014_auto_20190626_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='cutoff_time',
            field=models.PositiveIntegerField(default=1561573477.112953),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='pdf_time',
            field=models.PositiveIntegerField(default=1561573477.113),
        ),
    ]
